### ISSUE TITLE
Normalize inner whitespace of labels (esp. when using innerText)

### ISSUE THREAD

**Issue by gabrielgrant** [tradegecko/ember-semantic-test-helpers#18]
The [current implementation normalizes the label by trimming leading/trailing whitespace and converting to lowercase](https://github.com/tradegecko/ember-semantic-test-helpers/blob/master/addon-test-support/finders/find-by-aria/compute-aria.js#L54), but leaves internal whitespace untouched. This causes issues when matching buttons' innerText

For example, the innerText of the following element:

```
<button>
  <h3>Button Title</h3>
  <p>Description</p>
</button>
```
is
```
"
New input Data Source
Configure an input data source

"
```

The leading and trailing whitespace get stripped correctly, but it seems like the internal newline should be optional too.

**Comment by billybonks** [comment]
accidently closed :)

https://github.com/tradegecko/ember-semantic-test-helpers/pull/20 should fix this issue

**Comment by billybonks** [comment]
The goal and from what i understood in your comment, was to remove line breaks and replace them with a space. 

I think more trimming beyond that is not in the scope of the add-on, but you can replace the trim function in the config config.trim = somefunction. As long as u configure that before the app test runs it will use that function

**Comment by billybonks** [comment]
Actually on further inspection, i will just normalize all spaces to one space 👍 thanks for the suggestion.

**Comment by billybonks** [comment]
sorry for the delay, this is on 0.2.0 now :)

**Comment by gabrielgrant** [comment]
Awesome, thanks!

**Comment by billybonks** [comment]
going to close this
